name: Tagged release

on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    name: 'Tagged release'
    runs-on: 'ubuntu-latest'

    env:
      CLIENT_NAME: hotel-minimal-client
      BACKEND_NAME: hotel-minimal-backend
      BACKEND_URL: 'https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com'
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
      RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Get tag
        uses: olegtarasov/get-tag@v2.1
        id: getTag
      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: client/app/keystore
      - name: Prepare build directory
        run: rm -rf build && mkdir build
      - name: Build client
        run: |
          chmod +x ./scripts/build_client.sh
          ./scripts/build_client.sh $CLIENT_NAME-$GIT_TAG_NAME
      - name: Build backend
        run: |
          chmod +x ./scripts/build_backend.sh
          ./scripts/build_backend.sh $BACKEND_NAME-$GIT_TAG_NAME
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/*
      - name: Deploy backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: 'backend'
          stack: 'heroku-22'
          region: 'eu'
          procfile: 'web: java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/backend.jar'
          healthcheck: '${{ env.BACKEND_URL }}'
          rollbackonhealthcheckfailed: true
      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ env.GIT_TAG_NAME }}'
          prerelease: false
          files: build/*
